//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keeperScoreboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("keeperScoreboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bf4_bf_ani_1 {
            get {
                object obj = ResourceManager.GetObject("bf4_bf_ani_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bf4_bf_ani_2 {
            get {
                object obj = ResourceManager.GetObject("bf4_bf_ani_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bf4_bf_ani_3 {
            get {
                object obj = ResourceManager.GetObject("bf4_bf_ani_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgmainwindow {
            get {
                object obj = ResourceManager.GetObject("bgmainwindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap china {
            get {
                object obj = ResourceManager.GetObject("china", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;maps&quot;:[
        ///	{
        ///		&quot;gameExpansion&quot;: 0,
        ///		&quot;gameModes&quot;: [1,
        ///		2,
        ///		8,
        ///		32,
        ///		64,
        ///		512,
        ///		1024,
        ///		2097152,
        ///		16777216,
        ///		137438953472],
        ///		&quot;id&quot;: &quot;MP_Abandoned&quot;,
        ///		&quot;label&quot;: &quot;Zavod 311&quot;,
        ///		&quot;platforms&quot;: [1,
        ///		4,
        ///		32,
        ///		2,
        ///		64]
        ///	},
        ///	{
        ///		&quot;gameExpansion&quot;: 0,
        ///		&quot;gameModes&quot;: [1,
        ///		2,
        ///		8,
        ///		32,
        ///		64,
        ///		512,
        ///		1024,
        ///		2097152,
        ///		16777216,
        ///		137438953472],
        ///		&quot;id&quot;: &quot;MP_Damage&quot;,
        ///		&quot;label&quot;: &quot;Lancang Dam&quot;,
        ///		&quot;platforms&quot;: [1,
        ///		4,
        ///		32,
        ///		2,
        ///		64]
        ///	},
        ///	{
        ///		&quot;gameExpansion&quot;: 0,
        ///		&quot;game [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mapIds {
            get {
                return ResourceManager.GetString("mapIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;modes&quot;:[
        ///{
        ///	&quot;id&quot;: 64,
        ///	&quot;label&quot;: &quot;Conquest Large&quot;,
        ///	&quot;platforms&quot;: [1,
        ///	4,
        ///	32,
        ///	2,
        ///	64]
        ///},
        ///{
        ///	&quot;id&quot;: 1,
        ///	&quot;label&quot;: &quot;Conquest&quot;,
        ///	&quot;platforms&quot;: [1,
        ///	4,
        ///	32,
        ///	2,
        ///	64]
        ///},
        ///{
        ///	&quot;id&quot;: 2097152,
        ///	&quot;label&quot;: &quot;Obliteration&quot;,
        ///	&quot;platforms&quot;: [1,
        ///	4,
        ///	32,
        ///	2,
        ///	64]
        ///},
        ///{
        ///	&quot;id&quot;: 1024,
        ///	&quot;label&quot;: &quot;Domination&quot;,
        ///	&quot;platforms&quot;: [1,
        ///	4,
        ///	32,
        ///	2,
        ///	64]
        ///},
        ///{
        ///	&quot;id&quot;: 2,
        ///	&quot;label&quot;: &quot;Rush&quot;,
        ///	&quot;platforms&quot;: [1,
        ///	4,
        ///	32,
        ///	2,
        ///	64]
        ///},
        ///{
        ///	&quot;id&quot;: 8,
        ///	&quot;label&quot;: &quot;Squad Deathmatch&quot;,
        ///	&quot;platforms&quot;: [1,
        ///	4,
        ///	32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mapModes {
            get {
                return ResourceManager.GetString("mapModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_abandoned {
            get {
                object obj = ResourceManager.GetObject("mp_abandoned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_bank {
            get {
                object obj = ResourceManager.GetObject("mp_bank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_bloodout {
            get {
                object obj = ResourceManager.GetObject("mp_bloodout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_damage {
            get {
                object obj = ResourceManager.GetObject("mp_damage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_desert05 {
            get {
                object obj = ResourceManager.GetObject("mp_desert05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_downtown {
            get {
                object obj = ResourceManager.GetObject("mp_downtown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_eastside {
            get {
                object obj = ResourceManager.GetObject("mp_eastside", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_flooded {
            get {
                object obj = ResourceManager.GetObject("mp_flooded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_glades {
            get {
                object obj = ResourceManager.GetObject("mp_glades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_growhouse {
            get {
                object obj = ResourceManager.GetObject("mp_growhouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_hills {
            get {
                object obj = ResourceManager.GetObject("mp_hills", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_journey {
            get {
                object obj = ResourceManager.GetObject("mp_journey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_naval {
            get {
                object obj = ResourceManager.GetObject("mp_naval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_offshore {
            get {
                object obj = ResourceManager.GetObject("mp_offshore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_prison {
            get {
                object obj = ResourceManager.GetObject("mp_prison", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_resort {
            get {
                object obj = ResourceManager.GetObject("mp_resort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_siege {
            get {
                object obj = ResourceManager.GetObject("mp_siege", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_thedish {
            get {
                object obj = ResourceManager.GetObject("mp_thedish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp_tremors {
            get {
                object obj = ResourceManager.GetObject("mp_tremors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] orbitron_black {
            get {
                object obj = ResourceManager.GetObject("orbitron_black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://battlelog.battlefield.com/bf4/servers/show/PC/e843adeb-431c-4b55-818a-368ac42ce47e/Team-Verta-Match-Server/.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap usa {
            get {
                object obj = ResourceManager.GetObject("usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;compact&quot;: {
        ///    &quot;weapons&quot;: {
        ///      &quot;6240291&quot;: {
        ///        &quot;category&quot;: &quot;WARSAW_ID_P_CAT_KNIFE&quot;,
        ///        &quot;rareness&quot;: &quot;RarenessLevel_Distinguished&quot;,
        ///        &quot;name&quot;: &quot;WARSAW_ID_P_INAME_SHANK&quot;,
        ///        &quot;req&quot;: [
        ///          {
        ///            &quot;c&quot;: &quot;SP_as02_00&quot;,
        ///            &quot;t&quot;: &quot;a&quot;,
        ///            &quot;v&quot;: 1
        ///          }
        ///        ],
        ///        &quot;see&quot;: [
        ///          &quot;ic-weaponShank_lineart&quot;,
        ///          &quot;uic-weapon_unlockShank_fancy&quot;
        ///        ],
        ///        &quot;categoryType&quot;: &quot;Special&quot;,
        ///        &quot;slug&quot;: &quot;shank&quot;,
        ///        &quot;de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weaponData {
            get {
                return ResourceManager.GetString("weaponData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;weapons&quot;: [{
        ///			&quot;uic-weapon_unlockm416_fancy&quot;: {
        ///				&quot;unlockImageConfig&quot;: {
        ///					&quot;category&quot;: &quot;weapon_unlock&quot;,
        ///					&quot;slug&quot;: &quot;m416_fancy&quot;,
        ///					&quot;versions&quot;: {
        ///						&quot;smallinv&quot;: {
        ///							&quot;path&quot;: &quot;warsaw\/gamedata\/weapon_unlock\/smallinv.png&quot;,
        ///							&quot;isSprite&quot;: true,
        ///							&quot;height&quot;: 54,
        ///							&quot;name&quot;: &quot;smallinv&quot;,
        ///							&quot;width&quot;: 90
        ///						},
        ///						&quot;medium&quot;: {
        ///							&quot;path&quot;: &quot;warsaw\/gamedata\/weapon_unlock\/medium.png&quot;,
        ///							&quot;isSprite&quot;: true,
        ///							&quot;height&quot;: 88,
        ///							&quot;name&quot;: &quot;medium&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weaponDataTest {
            get {
                return ResourceManager.GetString("weaponDataTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp0_caspian {
            get {
                object obj = ResourceManager.GetObject("xp0_caspian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp0_firestorm {
            get {
                object obj = ResourceManager.GetObject("xp0_firestorm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp0_metro {
            get {
                object obj = ResourceManager.GetObject("xp0_metro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp0_oman {
            get {
                object obj = ResourceManager.GetObject("xp0_oman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_001 {
            get {
                object obj = ResourceManager.GetObject("xp1_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_002 {
            get {
                object obj = ResourceManager.GetObject("xp1_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_003 {
            get {
                object obj = ResourceManager.GetObject("xp1_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_004 {
            get {
                object obj = ResourceManager.GetObject("xp1_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_mallcops {
            get {
                object obj = ResourceManager.GetObject("xp1_mallcops", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_nights {
            get {
                object obj = ResourceManager.GetObject("xp1_nights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_projects {
            get {
                object obj = ResourceManager.GetObject("xp1_projects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp1_sawmill {
            get {
                object obj = ResourceManager.GetObject("xp1_sawmill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_001 {
            get {
                object obj = ResourceManager.GetObject("xp2_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_002 {
            get {
                object obj = ResourceManager.GetObject("xp2_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_003 {
            get {
                object obj = ResourceManager.GetObject("xp2_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_004 {
            get {
                object obj = ResourceManager.GetObject("xp2_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_cargoship {
            get {
                object obj = ResourceManager.GetObject("xp2_cargoship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_coastal {
            get {
                object obj = ResourceManager.GetObject("xp2_coastal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_museum02 {
            get {
                object obj = ResourceManager.GetObject("xp2_museum02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp2_precinct7 {
            get {
                object obj = ResourceManager.GetObject("xp2_precinct7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp3_marketpl {
            get {
                object obj = ResourceManager.GetObject("xp3_marketpl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp3_prpganda {
            get {
                object obj = ResourceManager.GetObject("xp3_prpganda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp3_urbangdn {
            get {
                object obj = ResourceManager.GetObject("xp3_urbangdn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp3_wtrfront {
            get {
                object obj = ResourceManager.GetObject("xp3_wtrfront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp4_arctic {
            get {
                object obj = ResourceManager.GetObject("xp4_arctic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp4_subbase {
            get {
                object obj = ResourceManager.GetObject("xp4_subbase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp4_titan {
            get {
                object obj = ResourceManager.GetObject("xp4_titan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xp5_night_01 {
            get {
                object obj = ResourceManager.GetObject("xp5_night_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
